//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbio.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount_AppliedToCategories
    {
        public int Discount_Id { get; set; }
        public int Category_Id { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
