//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbio.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturerTemplate
    {
        public ManufacturerTemplate()
        {
            this.Manufacturers = new HashSet<Manufacturer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ViewPath { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<Manufacturer> Manufacturers { get; set; }
        public virtual ManufacturerTemplate ManufacturerTemplate1 { get; set; }
        public virtual ManufacturerTemplate ManufacturerTemplate2 { get; set; }
    }
}
