//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbio.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionRecord
    {
        public PermissionRecord()
        {
            this.CustomerRoles = new HashSet<CustomerRole>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SystemName { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<CustomerRole> CustomerRoles { get; set; }
    }
}
