//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbio.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComponent
    {
        public ProductComponent()
        {
            this.Product_ProductComponent_Mapping = new HashSet<Product_ProductComponent_Mapping>();
        }
    
        public int Id { get; set; }
        public string ComponentName { get; set; }
        public bool IsActive { get; set; }
        public bool Deleted { get; set; }
        public bool IsVariablePrice { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<Product_ProductComponent_Mapping> Product_ProductComponent_Mapping { get; set; }
    }
}
