//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbio.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_ProductComponent_Mapping
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ComponentId { get; set; }
        public decimal Weight { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductComponent ProductComponent { get; set; }
    }
}
