//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbio.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_PriceComponent_Mapping
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int PricecomponentId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> Itemrate { get; set; }
    
        public virtual PriceComponent PriceComponent { get; set; }
        public virtual Product Product { get; set; }
    }
}
